- source/how-to/minio.rst
- source/understand/minio.rst
This is just me rambling from what I learnt the past few days.
Also I don't understand restructured text yet so we should fix that
too.
> Write some docs about operating and understanding minio

- pull_request_template.md
- source/how-to/administrate/minio.rst
- source/how-to/single-sign-on/azure/main.rst
- source/tutorial/index.rst
- source/understand/index.rst
> fix warning

- source/how-to/administrate/etcd.rst
Fills in one TODO, creates another TODO on the etcd page
> etcd instructions (1)

- source/conf.py
- wire-theme/LICENSE
- wire-theme/__init__.py
- wire-theme/_version.py
- wire-theme/about.html
- wire-theme/donate.html
- wire-theme/layout.html
- wire-theme/navigation.html
- wire-theme/relations.html
- wire-theme/static/alabaster.css_t
- wire-theme/static/custom.css
- wire-theme/support.py
- wire-theme/theme.conf
Based on alabaster with some tweaks
> Add wire theme

- src/how-to/administrate/etcd.rst
> Documented how to recover an etcd cluster where one node got corrupt

- src/how-to/administrate/users.rst
manual backoffice procedure (if backoffice is not available)
> manual backoffice procedure

- src/how-to/administrate/elasticsearch.rst
- src/how-to/administrate/users.rst
Documentation on manually using elasticsearch.
> elasticsearch manual deletion

- src/how-to/administrate/general-linux.rst
Some useful commands for TLS cert checking.
> document TLS cert checking

- src/how-to/single-sign-on/index.rst
- src/how-to/single-sign-on/trouble-shooting.rst
> How to collect sso debug information for customer support.

- src/how-to/single-sign-on/generic-setup.rst
- src/how-to/single-sign-on/trouble-shooting.rst
> SSO generic setup help

- src/how-to/single-sign-on/index.rst
- src/how-to/single-sign-on/trouble-shooting.rst
> SSO: trouble-shooting is also FAQ now; example SAML response.

- Makefile
- src/how-to/administrate/elasticsearch.rst
- src/how-to/install/configuration-options.rst
- src/how-to/install/helm.rst
- src/how-to/install/planning.rst
* migration from `nginx-lb-ingress` to `nginx-ingress-controller` & `nginx-ingress-services`
* note on trouble shoot ES in a situation where disk ran full
* some minor fixes I discovered back when I started and tried to deploy for the first time
> Reflect recent changes and gained experience (nginx-ingress-* charts, ES outage on-site)

- src/how-to/associate/deeplink.rst
- src/how-to/associate/index.rst
- src/how-to/index.rst
- src/how-to/install/troubleshooting.rst
> Add deeplink instructions

- src/how-to/single-sign-on/trouble-shooting.rst
This is coming up in CS discussions every now and then.
> Add FAQ entry on sso for owner (and why not).

- src/how-to/install/ansible-VMs.rst
> changes to the directions based on performing the last offline install.

- src/how-to/install/ansible-dependencies.rst
> minor language changes.

- src/how-to/associate/deeplink.rst
Added piece of information about deeplinking.
> add info on deeplinking

- src/how-to/post-install/ntp-check.rst
Fixed wording on the NTP checks
> Unfinished sentence in the NTP checks

- src/how-to/install/troubleshooting.rst
Fixes https://github.com/wireapp/wire-docs/issues/56
> Add hints on how to fix not-receiving-emails

- src/how-to/install/index.rst
- src/how-to/install/version-requirements.rst
> Add page about technologies and their proven versions

- src/how-to/install/includes/helm_dns-ingress-troubleshooting.inc.rst
Documents: https://github.com/zinfra/backend-issues/issues/1526
> [Helm] Add a note about cert-manager

- src/how-to/install/configuration-options.rst
* Show how to use http proxy.
* Show how to configure real push notifications
Relates to https://github.com/zinfra/backend-issues/issues/1233
> document http proxy setup

- src/how-to/install/configuration-options.rst
> notification docs update after email exchange

- src/how-to/post-install/checks.rst
- src/how-to/post-install/logrotation-check.rst
> Fix copy&paste error.

- src/understand/api-client-perspective/authentication.rst
> Replace html link with reStructuredText ref

- src/how-to/single-sign-on/trouble-shooting.rst
> How to map user data into scim users.

- src/how-to/configure-wire-clients/custom-certificates.md
> Documentation on custom certificates

- src/how-to/single-sign-on/trouble-shooting.rst
> Fix hyperlinks.

- src/how-to/install/configuration-options.rst
> Document how instance operator can bock creating new users, teams.

- src/understand/restund.rst
*SQPIT-287*
Implemented in https://github.com/wireapp/ansible-restund/pull/18
> [restund] Add information on preventing unwanted services exposure

- ci/compile-and-upload.yml
- ci/pr.yml
Needed as part of https://github.com/wireapp/wire-server-private/pull/286
> Concourse task in this repository

- src/how-to/administrate/minio.rst
Acknowledging latest role release: https://github.com/wireapp/ansible-minio/releases/tag/v2.1.0
> [minio] Add information on how to rotate credentials

- src/how-to/scim/index.rst
- src/index.rst
> Add how-to/scim/index.rst

- src/how-to/scim/index.rst
> Update SCIM docs

- src/how-to/scim/index.rst
> Update SCIM tenant URL

- src/how-to/scim/index.rst
> Add note about validity of scim token

- src/how-to/single-sign-on/trouble-shooting.rst
> Document our SAML NameID semantics.

- src/how-to/single-sign-on/trouble-shooting.rst
> Like this?

- src/how-to/install/dependencies.rst
> Actually also fetch the submodules

- src/how-to/install/ansible-VMs.rst
- src/how-to/install/kubernetes.rst
- src/how-to/install/planning.rst
> remove all references to ubuntu 16.04 to match the site survey

- src/understand/federation/introduction.rst
- src/understand/federation/roadmap.rst
This PR tries to fill the introduction to the federation part of the documentation with some life. I really wasn't sure what's meant to go into the intro for the kind of documentation that we want here, so feel free to give me some hints and I will revise the existing text.
> Stab at introduction to federation

- src/how-to/install/dependencies.rst
This is just a small addition to help guide the user through the flow of the installation.
> Add a link to the next page

- src/how-to/install/kubernetes.rst
> Minor change: put sd command on its own line

- src/how-to/install/kubernetes.rst
It's obvious to most users, but it's generally best to be explicit about all commands even the simplest ones.
> Add a cd command

- src/how-to/install/kubernetes.rst
> Add KUBECONFIG as the default value is currently wrong

- src/understand/federation/api.rst
- src/understand/federation/architecture.rst
- src/understand/federation/glossary.rst
A general pass over the API section to bring it up to date, reduce the level of detail and try to give a good high-level overview over what's going on. I'd greatly appreciate feedback on Section 4.6, where I put my best guess of how I would imagine the flows to work. Also, some feedback on how to bring Section 4.4 up to date would be great.
> Pass over federation API section

- src/understand/federation/roadmap.rst
> Federation roadmap update

- src/understand/federation/api.rst
> include message sending in federation API docs

- src/understand/federation/api.rst
- src/understand/federation/architecture.rst
- src/understand/federation/roadmap.rst
This PR includes a few minor fixes and improvements for a pre-release.
(Please don't mind the commit history. I'll squash before merge with a fitting commit message.)
> Minor fixes for pre-release

- src/conf.py
> Bump version to 0.0.2 after initial pre-release

- src/how-to/single-sign-on/trouble-shooting.rst
> Add to SSO FAQs: SSO feature connot be disabled

- src/how-to/single-sign-on/trouble-shooting.rst
This question comes from a customer.
> FAQ entry about distributing sso login code to users.

- src/how-to/install/configuration-options.rst
> On blocking user creation

- src/how-to/single-sign-on/trouble-shooting.rst
- src/understand/federation/api.rst
- src/understand/federation/architecture.rst
- src/understand/federation/index.rst
- src/understand/federation/introduction.rst
This PR integrates feedback from the release of 0.1.0. The changes are either editorial in nature or fix small bugs.
> Integrate feedback from the release of 0.1.0

- src/how-to/install/includes/helm_dns-ingress-troubleshooting.inc.rst
> Add SFTD to the list of domains.

- src/how-to/install/monitoring.rst
see wireapp/wire-server-deploy#486
-- nope, did not run checks
> Monitoring: nest prometheusSpec under prometheus in Helm values

- src/understand/overview.rst
> add description of pods

- src/how-to/install/helm.rst
> add sed command shortcuts for adding the secrets into the yaml file

- src/release-notes.rst
> Update release notes

- src/conf.py
> Bump version to 0.0.3

- src/understand/api-client-perspective/swagger.rst
Contents of the PR describes itself.  :)
> Elaborate on public swagger docs.

- src/understand/api-client-perspective/swagger.rst
> Fixup #216

- src/how-to/install/sft.rst
> Fix first SFT doc mistake

- src/how-to/install/ansible-VMs.rst
> change kubectl version result

- src/how-to/install/configure-federation.rst
Also mention the necessary configuration variables on the webapp for federation.
> mention webapp environment variables for federation

- src/how-to/single-sign-on/trouble-shooting.rst
> How to report SSO problems.

- src/how-to/install/ansible-VMs.rst
- src/how-to/install/kubernetes.rst
> Add minio vars

- src/how-to/administrate/users.rst
> adding mass invitation script documentation

- src/how-to/administrate/users.rst
Adding instructions on collecting Client instructions for the iOS and Android Wire Apps.
> Client log instructions

- src/how-to/administrate/users.rst
> adding first draft of the metrics grabbing instructions

- src/how-to/administrate/users.rst
> adding cannon example

- src/understand/federation/api.rst
- src/understand/federation/architecture.rst
- src/understand/federation/index.rst
- src/understand/federation/roadmap.rst
> Update understanding/federation/ docs to reflect M2 release.

- src/understand/api-client-perspective/authentication.rst
Corrected URL in example request.
> Fix remove cookie example

- src/how-to/install/configuration-options.rst
Gundeck Push Notification Configuration is now communicated in YAML.
> update Push Notification section

- src/understand/single-sign-on/design.rst
> Mark page linking to new target as orphan to resolve warning

- src/how-to/install/configure-federation.rst
- src/how-to/install/index.rst
- src/how-to/install/tls.rst
This is an attempt to collect all TLS configurations at one single location and to document the current state so we can move forward to a more consolidated configuration.
Marked as WIP, since some details regarding SFTD are not clear yet.
> Document different places to configure TLS settings

- src/security-responses/cve-2021-44521.md
> Add notice of not being affected of CVE-2021-44521

- src/release-notes.rst
> Add release notes for 4.2.0

- src/how-to/administrate/general-linux.rst
- src/how-to/administrate/operations.rst
- src/how-to/administrate/users.rst
This PR improves the TOC of `how-to/administrate/` and makes one note block more visible
> Fix formating in several places

- src/how-to/administrate/users.rst
This PR adds the documentation how to reset session cookies.
> Add documentation regarding handling of Cookies

- src/release-notes.rst
> version fixes

- src/release-notes.rst
> Release Notes 4.9.0
