wireapp/wire-docs

- Makefile
- source/conf.py
Allows to run `make docs-administrate`, which produces a partial documentation (in this case: only the pages from the how-to/administrate dir). This can be useful when sending documentation pages to someone.
> Support only building partial documentation: administrate section

- src/how-to/api-client-perspective/authentication.rst
- src/how-to/api-client-perspective/index.rst
port to rst, adapt, and publish API docs page on authentication
> port, adapt, and publish API docs page on authentication

- src/how-to/install/troubleshooting.rst
CORS issues have repeatedly come up during installation, e.g. [here](https://github.com/wireapp/wire-server-deploy/issues/186).
> Add section about CORS

- src/how-to/administrate/restund.rst
More information about TURN servers as seen by clients.
> turn check calls/config

- src/understand/single-sign-on/design.rst
Not sure we want to link to random blog posts like this from our own product docs, but i like it!  So if I get anybody to approve this, it'll happen.  :)
> Add link to saml&beer blog post.

- src/how-to/install/ansible-VMs.rst
- src/how-to/install/ansible-dependencies.rst
add note about keeping time in sync, and directions for using an apt mirror while installing elasticsearch.
> add note about keeping time in sync, and directions for using an apt mirror while installing elasticsearch.

- src/how-to/administrate/index.rst
- src/how-to/administrate/kubernetes/certificate-renewal/index.rst
- src/how-to/administrate/kubernetes/certificate-renewal/scenario-1_k8s-v1.14-kubespray.rst
- src/how-to/administrate/kubernetes/index.rst
* add a first scenario explaining cert renewal for a 3-master K8s v1.14 setup installed with Kubespray
* add additional structure to reflect (fingers crossed) future k8s content
* typo
> Add documentation on how to renew TLS certificates used by certain K8s components

- src/how-to/administrate/kubernetes/certificate-renewal/scenario-1_k8s-v1.14-kubespray.rst
Some minor changes to the certificate renewal docs.
> Cert update

- .editorconfig
- .gitignore
- Makefile
- README.md
* `dev-install` allows to install dependencies for a local development mode by utilizing python's `venv` module
* `dev-run` starts a local web server and file watcher
* mention this approach to make it more visible for other contributors
* add editorconfig to ensure tags in makefiles across IDEs
* remove `clean` target since it's neither defined nor is it a sphinx builder
* refactor Makefile to use absolute (relative to the Makefile) paths and applied some best practice (.PHONY right next to the target)
> Add local dev mode without docker as dependency

- src/how-to/administrate/general-linux.rst
Documentation on how to see certificate validity from a kubernetes machine.
> certificate one-liner

- src/how-to/index.rst
> we moved this elsewhere.

- src/how-to/install/ansible-VMs.rst
- src/how-to/install/helm.rst
- src/how-to/install/logging.rst
- src/how-to/single-sign-on/trouble-shooting.rst
- src/understand/minio.rst
I fixed some typos and added info about how restund playbook also manipulates hostname.
> fixed typos and added info about restund playbook

- src/how-to/install/kubernetes.rst
with 4 cores I was running into trouble starting all the kubernetes in wire-server
* [x ] I ran `make` on this branch to build the docs and there are **no WARNINGs**.
* [ x] After running `make`, I looked at the output by opening build/html/index.html in a browser and I'm satisfied with the rendering.
> with 4 cores there will be an error installing wire-server

- src/how-to/single-sign-on/trouble-shooting.rst
> Extend SAML FAQ

- src/how-to/administrate/kubernetes/certificate-renewal/scenario-1_k8s-v1.14-kubespray.rst
A customer recently run into the issue of not being able to authorize against the kube-api
after going through a renewal process.
> [K8s:cert-renewal] Add a note about reconfiguring the user's kubeconfig

- src/how-to/associate/deeplink.rst
This PR only changes a small punctuation hiccup. For consistency, only one dot is needed.
``src/how-to/install/includes/helm_dns-ingress-troubleshooting.inc.rst:134: WARNING: duplicate label helm_prod_troubleshooting, other instance in /mnt/src/how-to/install/helm.rst``
> deeplink.rst: Removed superfluous dot

- src/how-to/associate/deeplink.rst
A customer spent a fair amount trying to debug this: turned out they had some missing keys in the JSON file
> Explain that all keys in the deeplink need to be set

- src/how-to/administrate/restund.rst
- src/how-to/index.rst
- src/how-to/post-install/index.rst
- src/how-to/post-install/logrotation-check.rst
Relates to zinfra/backend-issues#1462
> Docs to configure logretention of max 72h

- src/how-to/install/troubleshooting.rst
Another customer has run into this problem, this time when using the `team-settings` app. Hopefully this will make it clearer that all web applications need these headers.
> Add more info on CSP headers

- src/how-to/post-install/index.rst
> Depth:1 instead of 2 for TOC on verify index

- src/how-to/post-install/logrotation-check.rst
The previous command didn't quite work as expected for older logs, and the namespace may not be 'wire'.
> adapt logrotation documentation page for clarity

- README.md
- src/how-to/single-sign-on/azure/main.rst
- src/how-to/single-sign-on/centrify/main.rst
- src/how-to/single-sign-on/generic-setup.rst
- src/how-to/single-sign-on/okta/main.rst
Fixes https://github.com/zinfra/backend-issues/issues/1768
> Patch holes in SSO docs.

- src/how-to/single-sign-on/generic-setup.rst
> Fix link to backend config in sso howto.

- Makefile
- src/conf.py
- src/how-to/install/aws-prod.rst
- src/how-to/install/helm-prod.rst
- src/how-to/install/helm.rst
- src/how-to/install/includes/helm_dns-ingress-troubleshooting.inc.rst
> Add missing https

- src/how-to/install/helm-prod.rst
- src/how-to/install/helm.rst
> [install] Replace Helm version occurrences of v2 with v3

- src/how-to/install/index.rst
- src/how-to/install/sft.rst
> add sftd docs

- src/understand/overview.rst
> minor spelling / editing

- src/how-to/single-sign-on/trouble-shooting.rst
> Spar FAQ item on submitting CS requests.

- .github/workflows/ci.yml
- src/how-to/install/sft.rst
- src/understand/restund.rst
> Clarify some things about restund port ranges

- src/conf.py
- src/understand/federation/api.rst
- src/understand/federation/architecture.rst
- src/understand/federation/configuration.rst
- src/understand/federation/faq.rst
- src/understand/federation/glossary.rst
- src/understand/federation/index.rst
- src/understand/federation/introduction.rst
- src/understand/federation/roadmap.rst
- src/understand/index.rst
> Federationdoc - initial structure with TODOs

- .github/workflows/ci.yml
- nix/default.nix
- poetry.lock
- pyproject.toml
- shell.nix
- src/conf.py
Improves the sidebar to include the full table of contents, making navigation easier.
Example screenshot with this extension:
instead of the current
WIP:
> enable fulltoc extension

- Dockerfile
- Dockerfile-poetry
- Makefile
- ci/compile-and-upload.yml
- ci/pr.yml
Create a docker image based on nix, rather than poetry. This simplifies the concourse tasks.
> Nix docker image

- README.md
- src/understand/federation/api.rst
Also, update README with heading conversation
> Add docs for the federation API 

- src/understand/federation/architecture.rst
- src/understand/federation/errors.rst
This PR ticks of the TODOs in the `Discovery`, `Authentication` and `Authorization` sections. I tried to be reasonably precise about how the procedures work, but please let me know if there are things missing. I also didn't yet document anything in the `federation configuration` section, so that's still a TODO.
> Describe discovery, authentication and authorization

- Dockerfile
- Makefile
I am not sure what purpose the Entrypoint was serving, but it was causing `make docs` to fail. 
> Fix docker workflow

- src/index.rst
- src/release-notes.rst
This is currently Markdown formatted; as I was copying things from the
wire-server release notes.
NOTE:  2.103.0 is missing from CI but it is needed
> WIP: Release notes

- src/understand/federation/api.rst
- src/understand/federation/glossary.rst
This PR adds a brief discussion around qualified IDs and names, as well as some "definitions", which are really just examples. There are still some todos, as I wasn't sure how formal we want this section to be. Is there already a place where the user UUIDs and names are (formally) defined? If not, this might be a good place to do it.
Let me know what you think!
> Add definitions for qualified IDs and names.

- Makefile
- src/how-to/administrate/etcd.rst
- src/how-to/administrate/kubernetes/index.rst
- src/how-to/administrate/kubernetes/restart-machines/index.rst
- src/how-to/administrate/kubernetes/upgrade-cluster/index.rst
Adds docs on how to restart machines that are part of a Kubernetes cluster. Additionally, it add entrypoints on how to upgrade a K8s cluster, and some external links on how to deal with etcd in the context of K8s.
> [admin:k8s] Add information on how to restart machines

- src/how-to/install/sft.rst
- src/understand/minio.rst
- src/understand/restund.rst
- src/understand/sft.rst
* typos
* restunds dont talk to their own
> [restund/sft] Gve some context for the SFT diagram

- src/understand/single-sign-on/design.rst
> Link historical yet still valid email on xmlsec.

- src/how-to/scim/index.rst
> updated scim token mention

- Makefile
"latest" may be too old for someone who downloaded "latest" before.
We can either always pull before running; or bump the version each time there is a relevant tooling change. This implements the latter approach for now (needs to be manually bumped if the nix-based tooling changes, e.g. new plugins).
fixes #143
> lock default docker tag to an explicit version

- src/how-to/install/kubernetes.rst
If run as-is the command tries to address a hosts.ini file in the current folder, but the .ini file is actually in inventory/demo/
> Add full path for sed command

- src/how-to/install/kubernetes.rst
Calling the .ini file hosts.example-demo.ini  when the file in the Docker is actually called hosts.example.ini
> The cp command had the wrong filename

- src/how-to/install/helm-prod.rst
- src/how-to/install/helm.rst
- src/how-to/install/logging.rst
- src/how-to/install/monitoring.rst
Links appear to have been broken since their introduction due to RST not supporting nesting links in italics (or any inline markup, for that matter, unless you're down for some [*interesting* workarounds](https://stackoverflow.com/a/4836544/3826702)).
This change uses the "note" box markup for the affected links (which was already used in one instance).
> fix broken link to Helm value overrides section anchor

- src/conf.py
As the title says. The added option makes `rst2pdf` shrink anything that doesn't fit within the page. From what I can see, this only affects the SRV record in the `Discovery` section.
> Simple fix to keep SRV record in the federation docs within page

- Makefile
- src/conf.py
As the title says, this PR does some minor changes to the Makefile and the `conf.py` to allow for compilation to LaTeX. It also adds a `release` field, which contains the same value as the `version` field. From what I could see, this doesn't change anything in the extracted HTML docs, but since LaTeX seems to only display the `release`, it seems like a worthwhile workaround for now.
> Enable compilation to latex and add release field

- Makefile
- nix/default.nix
This adds the texlive ecosystem of tools (note to nix people: `pkgs.texlive.combined.scheme-medium` was not enough), which adds a few extra GB initially; and adds a target to create a PDF via latex. That resulting PDF looks nicer than the rst2pdf tooling.
Once a docker image gets built with this tooling, we can add another inside-docker target.
> PDF via latex target, and the full texlive dependencies

- src/understand/federation/api.rst
- src/understand/federation/architecture.rst
- src/understand/federation/glossary.rst
- src/understand/federation/introduction.rst
This PR renames the `Ingress` to `Federation Ingress` to distinguish it from the other ingress component that deals with non-federation requests. The second ingress is not part of the federation docs, but if we don't rename, we will run into a collision sooner or later when this gets merged with non-federation documentation.
This PR also capitalizes all mentaions of `Federator` and `Federation Ingress` and typesets them as inline code.
> Rename ingress to federation ingress and harmonize capitalization of Federator and Federation Ingress

- Makefile
When new dependencies are introduced, but if contributors use docker rather than the nix setup, it's necessary to bump the docker tag here.
> Update docker image to include rtd theme and texlive binaries

- src/how-to/associate/deeplink.rst
- src/release-notes.rst
Update of deeplink documentation after merging of https://github.com/wireapp/wire-server/pull/1889
> adapt deeplink docs

- src/release-notes.rst
There were already these warnings:
```
/tmp/tmpkcnfkwvb/4eac54450dadf167a8cddec34d503c362e6a86e3/src/release-notes.rst:125: WARNING: Title underline too short.
Chat Release 2.111.0
============
/tmp/tmpkcnfkwvb/4eac54450dadf167a8cddec34d503c362e6a86e3/src/release-notes.rst:125: WARNING: Title underline too short.
Chat Release 2.111.0
============
/tmp/tmpkcnfkwvb/fb87f2bf733dd886a83360d772aa6e2aed7c9d20/src/release-notes.rst:125: WARNING: Title underline too short.
Chat Release 2.111.0
============
/tmp/tmpkcnfkwvb/fb87f2bf733dd886a83360d772aa6e2aed7c9d20/src/release-notes.rst:125: WARNING: Title underline too short.
Chat Release 2.111.0
============
```
> Add release notes for 2.117.0 and 2.118.0

- src/how-to/install/ansible-VMs.rst
- src/how-to/install/index.rst
- src/how-to/install/restund.rst
As per JCT-72, moving Restund installation instructions into their own page, like SFT has.
Need to still leave a link to these instructions in the place these instrucitons are currently located.
> Dedicated «installing restund» page

- Dockerfile
Upstream has updated the nix docker image to nix 2.5, which is now no longer based on Alpine Linux. The new version of the image seems to be completely broken (building and installing derivations doesn't work at all), so I've pinned the image we build the docker image from to the last known good version, 2.3.12.
> Pin nix docker image version in Dockerfile

- src/how-to/install/configure-federation.rst
Document new mandatory `federationDomain` setting for cargohold, introduced by https://github.com/wireapp/wire-server/pull/1990.
> Document cargohold federation domain option

- src/how-to/install/configure-federation.rst
Document FAQs for TLS configuration for federation.
> Document TLS ciphers state of things for federation

- src/understand/federation/api.rst
This PR removes the currently existing warning, when generating the rendered output
> Fix internal reference link to "Backend domain"

- README.md
- src/conf.py
`recommonmark` was already included in the nix extensions (as a dependency to other packages) but not activated. Go wild creating markdown file!
To see that this works, see https://github.com/wireapp/wire-docs/pull/270
> Support markdown

- README.md
This PR will correct links in README.md, which were pointing to no longer working targets
> Fix links in RADME.md

- src/index.rst
I think that the state of the current documentation is self-evident, no need to mention a specific date that the state refers to
--- 
I tried to execute the step from the checklist, but I could not get 'sphinx' to work on my Windows WLS environment. I gave up after 20 minutes, I believe this is a small change that does not warrant this effort, but feel free to say otherwise if you disagree.
> Fix: removed outdated date reference

- src/release-notes.rst
adding the latest releases from the wire-server changelog, using the tags to map dates to versions
kept the dates in as that sounds like helpful information
> adding latest releases

- src/how-to/install/configure-federation.rst
WARNINGs when this branch is built with `make html`:
```
sphinx-build -M html "/home/sven/src/wire-docs/src" "/home/sven/src/wire-docs/build" -q
/nix/store/brp9dz5v47zxwkskffy57pzf8fmng2rm-python3-3.8.8-env/lib/python3.8/site-packages/recommonmark/parser.py:75: UserWarning: Container node skipped: type=document
warn("Container node skipped: type={0}".format(mdnode.t))
sphinx-multiversion "/home/sven/src/wire-docs/src" "/home/sven/src/wire-docs/build/html" -q
/nix/store/brp9dz5v47zxwkskffy57pzf8fmng2rm-python3-3.8.8-env/lib/python3.8/site-packages/rst2pdf/rson.py:119: FutureWarning: Possible nested set at position 2
splitter = re.compile(pattern).split
/nix/store/brp9dz5v47zxwkskffy57pzf8fmng2rm-python3-3.8.8-env/lib/python3.8/site-packages/r …
```
> Fix federation allow list examples
